### PR TITLE
Firefox support

### LINKED ISSUE #2: firefox support
Is very broken on firefox, chrome/chromium works fine

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #2

- [x] make recording work

### CODE REVIEW

**Comment by Akuli** [comment]
Currently records silence on firefox, no idea why

File: js/audioManager.js [hunk 1]
```diff
@@ -135,15 +153,32 @@ export class AudioManager {
     }
   }
 
+  // Called after changing something in this.loopAudioBuffer
+  audioDataChanged() {
+    if (this._bufSource !== null) {
+      this._bufSource.stop();
+      this._bufSource.disconnect();
+    }
```
Comment (Akuli) [inline js/audioManager.js:161]: Would be nice to skip the rest of this on chromium when this is called not for first time

File: js/audioManager.js [hunk 2]
```diff
@@ -135,15 +153,32 @@ export class AudioManager {
...
+    this._bufSource.buffer = this.loopAudioBuffer;
+    this._bufSource.loop = true;
+    this._bufSource.connect(this._connectBufSourceHere);
+    this._bufSource.start(0, this._ctx.currentTime % this.loopAudioBuffer.duration);
+  }
+
   async addMetronomeTicks(track) {
     const baseUrl = window.location.pathname.replace(/[^\/]*\/looper.html$/, '');
-    const arrayBuffer = await downloadBinaryFileAsArrayBuffer(baseUrl + 'metronome.flac');
+    const arrayBuffer = await downloadBinaryFileAsArrayBuffer(baseUrl + 'metronome.wav');
```
Comment (Akuli) [inline js/audioManager.js:174]: This really needed or was that some other bug?

File: js/audioManager.js [hunk 3]
```diff
@@ -162,22 +197,34 @@ export class AudioManager {
 
     const chunks = [];  // contains blobs
     this._recordState.mediaRecorder.ondataavailable = async(event) => {
+      console.log(event.data);
```
Comment (Akuli) [inline js/audioManager.js]:
```suggestion
```

File: js/firestore.js [hunk 4]
```diff
@@ -42,6 +42,7 @@ export async function init() {
 
   // Can't use query params because changing them causes a reload
   let bpm, beatCount;
+  window.location.hash='#60,4';
```
Comment (Akuli) [inline js/firestore.js]:
```suggestion
```

File: js/track.js [hunk 5]
```diff
@@ -180,7 +177,7 @@ export class TrackManager {
     }
     this._tracks.splice(index, 1);
 
-    track.channel.floatArray.fill(0);
+    track.channel.getFloatArray().fill(0);
```
Comment (Akuli) [inline js/track.js]: This might not be sufficient on firefox.

```suggestion
    const floatArray = track.channel.getFloatArray();
    floatArray.fill(0);
    track.channel.setFloatArray(floatArray);

```

**Comment by Akuli** [comment]
Recording works now, idk why was broken

File: js/audioManager.js [hunk 6]
```diff
@@ -28,10 +28,8 @@ async function downloadBinaryFileAsArrayBuffer(fileUrl) {
 }
 
 // returns array of GainNodes for adjusting volume
```
Comment (Akuli) [inline js/audioManager.js]: Comment should move
